# Generated by Django 3.2.5 on 2021-08-03 08:09

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('sp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
                ('rating', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('truck_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('truck_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('ifLogged', models.BooleanField(default=False)),
                ('token', models.CharField(default='', max_length=500, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderUser',
            fields=[
                ('serviceProviderUser_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.serviceprovider')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderTruck',
            fields=[
                ('serviceProviderTruckId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.serviceprovider')),
                ('truck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.trucks')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('dropoff_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_date', models.DateTimeField()),
                ('cargo_items', models.JSONField()),
                ('serice_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.serviceprovider')),
                ('serviceProviderTruck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.trucks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapi.user')),
            ],
        ),
    ]
